spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request.
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  paths-to-match: /**
  packages-to-scan: br.com.mercadolivre.bootcampw2.grupo11.socialmeli.controllers
  show-actuator: true
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true
    path: /swagger-ui.html

server:
  servlet:
    context-path: /v1

app:
  title: social-meli
  description: @project.description@
  version: @project.version@